CHANNEL = '#MissingSemicolon'
ADMINS = ['admin']
SERVICES_NAME = 'NickServ@Services.Host.com'
SERVICES_ACCOUNT = 'ProtectServ'
SERVICES_PASSWORD = 'password'
AUTHENTICATION_COMMAND = 'AUTH'
COLOR_CODE = '\0034,1 '
COMMAND = '.'
DEFAULT_NICK = 'ProtectServ'
SERVER = 'irc.Beirut.com'
SERVER_PORT = 8000
SERVER_SSL = True
