CHANNEL = '#MissingSemicolon'
ADMINS = ['admin']
SERVICES_PASSWORD = 'password'
COLOR_CODE = '\0034,1 '
COMMAND = '.'
DEFAULT_NICK = 'ProtectServ'
SERVER = 'irc.Beirut.com'
SERVER_PORT = 8000
SERVER_SSL = True
